name: 'Create Repository'
description: "Creates a repository conforming to the organization's requirements."
inputs:
  apiToken:
    description: 'The GitHub token to use when accessing the API'
    required: true
  issueNumber:
    description: 'The ID of the issue that has the parameters for creating the repository'
    required: true
  repoToken:
    description: 'The GITHUB_TOKEN from the secrets context. This is used to add comments to the issue.'
    required: true
runs:
  using: 'node16'
  main: 'index.js'