name: new-repo-workflow

on:
  issue_comment:
    types: [created]

jobs:
  create-repo:
    name: Create Rpo
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Process command
        uses: ./
        with:
          apiToken: ${{ secrets.API_TOKEN }}
          issueId: ${{ github.event.issue.id }}

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      
      - name: Dump steps context
      
        run: echo '${{ toJSON(steps) }}'
      
      - name: Dump runner context
      
        run: echo '${{ toJSON(runner) }}'
      
      - name: Dump strategy context
      
        run: echo '${{ toJSON(strategy) }}'
      
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'