name: new-repo-workflow

on:
  issue_comment:
    types: [created]

jobs:
  create-repo:
    name: Create Rpo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Process command
        uses: ./
        with:
          apiToken: ${{ secrets.API_TOKEN }}
          issueNumber: ${{ github.event.issue.number }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
